// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAws31Ty5WjHxqexB8PqnmzNKUgsmofk_E',
    appId: '1:680129385454:web:091745d228519a5a6bf4ff',
    messagingSenderId: '680129385454',
    projectId: 'smartstudy-95da6',
    authDomain: 'smartstudy-95da6.firebaseapp.com',
    storageBucket: 'smartstudy-95da6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc78HrwIU5CXXzlcFZEnsOn9vsdfND1Ik',
    appId: '1:680129385454:android:5c8f9567ee9a17856bf4ff',
    messagingSenderId: '680129385454',
    projectId: 'smartstudy-95da6',
    storageBucket: 'smartstudy-95da6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW-URymjYkcReZS5Lb73ZvNKPlz_3Ikh8',
    appId: '1:680129385454:ios:f5c50c88b0cc23b96bf4ff',
    messagingSenderId: '680129385454',
    projectId: 'smartstudy-95da6',
    storageBucket: 'smartstudy-95da6.firebasestorage.app',
    iosBundleId: 'com.example.smartStudy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW-URymjYkcReZS5Lb73ZvNKPlz_3Ikh8',
    appId: '1:680129385454:ios:f5c50c88b0cc23b96bf4ff',
    messagingSenderId: '680129385454',
    projectId: 'smartstudy-95da6',
    storageBucket: 'smartstudy-95da6.firebasestorage.app',
    iosBundleId: 'com.example.smartStudy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAws31Ty5WjHxqexB8PqnmzNKUgsmofk_E',
    appId: '1:680129385454:web:099500471cfd68f86bf4ff',
    messagingSenderId: '680129385454',
    projectId: 'smartstudy-95da6',
    authDomain: 'smartstudy-95da6.firebaseapp.com',
    storageBucket: 'smartstudy-95da6.firebasestorage.app',
  );
}
